// frontend/src/pages/layout.svelte
<script lang="ts">
  import { Toaster } from "svelte-sonner"
  import Header from "./header.svelte"
  import Main from "./main.svelte"
</script>

<Toaster position="top-center" duration={1000} closeButton />
<!-- 外层容器，占满全屏 -->
<div class="h-screen w-full bg-gray-200 flex overflow-hidden">
  <!-- 内层圆角容器，占满外层空间 -->
  <div
    class="flex flex-col flex-1 rounded-lg bg-white shadow-lg overflow-hidden m-2"
  >
    <Header />
    <Main />
  </div>
</div>

// frontend/src/components/Layout.vue
<template>
  <!-- 外部容器 -->
  <div class="h-screen flex flex-col bg-neutral-100 dark:bg-neutral-900 p-4 overflow-hidden">
    <!-- 圆角容器 -->
    <div class="flex-1 flex flex-col overflow-hidden rounded-xl bg-white dark:bg-neutral-900 shadow-sm ring-1 ring-neutral-200 dark:ring-neutral-800">
      
      <header class="h-14 shrink-0 flex items-center px-4 border-b border-neutral-200 dark:border-neutral-800">
        <div class="flex items-center gap-2">
          <UIcon name="i-logos-nuxt-icon" class="size-6" />
          <span class="font-bold text-sm">我的系统</span>
        </div>
      </header>

      <main class="flex-1 overflow-y-auto p-4">
        <RouterView />
      </main>
      
    </div>
  </div>
</template>
